CREATE TABLE [dbo].[Cuenta] (
    [id_cuenta]                    INT          IDENTITY (1, 1) NOT NULL,
    [id_tipo_cuenta]               INT          NOT NULL,
    [denominacion1]                VARCHAR (50) NOT NULL,
    [denominacion2]                VARCHAR (50) NOT NULL,
    [id_tipo_identificacion]       INT          NULL,
    [numero_identificacion]        VARCHAR (20) NULL,
    [numero_CUIT]                  VARCHAR (11) NULL,
    [sexo]                         VARCHAR (1)  NULL,
    [id_nacionalidad]              INT          NULL,
    [fecha_nacimiento]             DATETIME     NULL,
    [id_canal]                     INT          NOT NULL,
    [id_estado_cuenta]             INT          NOT NULL,
    [id_version_tyc]               INT          NULL,
    [flag_envio_novedades]         BIT          NULL,
    [fecha_alta]                   DATETIME     NULL,
    [usuario_alta]                 VARCHAR (20) NULL,
    [fecha_modificacion]           DATETIME     NULL,
    [usuario_modificacion]         VARCHAR (20) NULL,
    [fecha_baja]                   DATETIME     NULL,
    [usuario_baja]                 VARCHAR (20) NULL,
    [version]                      INT          CONSTRAINT [DF_Cuenta_version] DEFAULT ((0)) NOT NULL,
    [telefono_movil]               VARCHAR (10) NULL,
    [telefono_fijo]                VARCHAR (10) NULL,
    [flag_cambio_pendiente]        BIT          DEFAULT ((0)) NULL,
    [flag_informado_a_facturacion] BIT          CONSTRAINT [DF_Cuenta_flag_informado_a_facturacion] DEFAULT ((0)) NULL,
    [id_operador_celular]          INT          NULL,
    [id_banco_adhesion]            INT          NULL,
    [flag_factor_validacion]       BIT          DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Cuenta] PRIMARY KEY CLUSTERED ([id_cuenta] ASC) WITH (FILLFACTOR = 80),
    CONSTRAINT [FK_Cuenta_Canal_Adhesion] FOREIGN KEY ([id_canal]) REFERENCES [dbo].[Canal_Adhesion] ([id_canal]),
    CONSTRAINT [FK_Cuenta_Estado] FOREIGN KEY ([id_estado_cuenta]) REFERENCES [dbo].[Estado] ([id_estado]),
    CONSTRAINT [FK_Cuenta_id_banco_adhesion] FOREIGN KEY ([id_banco_adhesion]) REFERENCES [dbo].[Banco] ([id_banco]),
    CONSTRAINT [FK_Cuenta_id_operador_celular] FOREIGN KEY ([id_operador_celular]) REFERENCES [dbo].[Operador_Celular] ([id_operador_celular]),
    CONSTRAINT [FK_Cuenta_Nacionalidad] FOREIGN KEY ([id_nacionalidad]) REFERENCES [dbo].[Nacionalidad] ([id_nacionalidad]),
    CONSTRAINT [FK_Cuenta_Tipo_id_tipo_cuenta] FOREIGN KEY ([id_tipo_cuenta]) REFERENCES [dbo].[Tipo] ([id_tipo]),
    CONSTRAINT [FK_Cuenta_Tipo_id_tipo_identificacion] FOREIGN KEY ([id_tipo_identificacion]) REFERENCES [dbo].[Tipo] ([id_tipo]),
    CONSTRAINT [FK_Cuenta_TyC] FOREIGN KEY ([id_version_tyc]) REFERENCES [dbo].[TyC] ([id_version])
);

